let DATA=null;const $=id=>document.getElementById(id);const vals=s=>[...s.selectedOptions].map(o=>o.value);
const esc=s=>String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const fmt=n=>n==null||Number.isNaN(n)?"—":new Intl.NumberFormat("en-IN",{maximumFractionDigits:0}).format(n);
const ctr=n=>n==null||Number.isNaN(n)?"—":((n<=1?n*100:n).toFixed(2)+"%");
fetch("data.json").then(r=>r.json()).then(d=>{DATA=d;init()}).catch(()=>document.body.innerHTML="<div style='padding:40px;font-family:Arial'><h2>data.json not found</h2><p>Keep all four files in the same folder.</p></div>");
function init(){ $("updated").textContent=DATA.updated;[...new Set(DATA.rows.map(r=>r.state).filter(Boolean))].sort().forEach(s=>{let o=new Option(s,s);$("state").add(o)});DATA.properties.forEach(p=>$("property").add(new Option(p,p)));$("property").selectedIndex=0;updateCities();$("state").onchange=updateCities;$("check").onclick=search;$("reset").onclick=()=>location.reload();}
function updateCities(){let states=vals($("state")),old=vals($("city"));let cs=[...new Set(DATA.rows.filter(r=>!states.length||states.includes(r.state)).map(r=>r.city))].sort();$("city").innerHTML="";cs.forEach(c=>{let o=new Option(c,c);if(old.includes(c))o.selected=true;$("city").add(o)})}
function search(){let states=vals($("state")),cities=vals($("city")),prop=$("property").value;if(!states.length||!cities.length||!prop){alert("Please select State, City and Media Property.");return}let rows=DATA.rows.filter(r=>states.includes(r.state)&&cities.includes(r.city)&&r.property===prop);$("selection").hidden=false;$("selection").innerHTML=`<b>Selected:</b> ${states.length} state${states.length>1?"s":""} • ${cities.length} cit${cities.length>1?"ies":"y"} • ${esc(prop)}`;if(!rows.length){$("empty").hidden=false;$("results").hidden=true;$("empty").innerHTML="<div class='searchicon'>!</div><h2>No impression data available</h2><p>No records match your selection.</p>";return}$("empty").hidden=true;$("results").hidden=false;$("location").textContent=states.join(", ");$("heading").textContent=cities.length===1?cities[0]+" – "+prop:cities.length+" Cities – "+prop;render(rows)}
function render(rows){let max=Math.max(...rows.map(r=>r.impressions||0),1);$("cards").innerHTML=rows.map(r=>`<div class="card property-card ${r.impressions===max?"top":""}"><div class="property">${esc(r.city)}</div><div class="unit">${esc(r.state)} • ${esc(r.property)}</div><div class="big">${fmt(r.impressions)}</div><div class="unit">MONTHLY IMPRESSIONS</div><div class="metrics"><div class="metric"><span>Viewable</span><b>${fmt(r.viewable)}</b></div><div class="metric"><span>Clicks</span><b>${fmt(r.clicks)}</b></div><div class="metric"><span>CTR</span><b>${ctr(r.ctr)}</b></div></div></div>`).join("");$("tbody").innerHTML=rows.map(r=>`<tr><td>${esc(r.state)}</td><td><b>${esc(r.city)}</b></td><td>${esc(r.property)}</td><td>${fmt(r.impressions)}</td><td>${fmt(r.viewable)}</td><td>${fmt(r.clicks)}</td><td>${ctr(r.ctr)}</td></tr>`).join("");let text=rows.map(r=>`${r.state} – ${r.city} – ${r.property}: ${fmt(r.impressions)} monthly impressions | Viewable: ${fmt(r.viewable)} | Clicks: ${fmt(r.clicks)} | CTR: ${ctr(r.ctr)}`).join("\n");$("copy").onclick=()=>navigator.clipboard?.writeText(text).then(()=>alert("Results copied"))}
